import type { NextPage } from "next";
import Head from "next/head";
// import HomeScreen from "../src/screens/HomeScreen";
import dynamic from "next/dynamic";

const HomeScreen = dynamic(() => import("../src/screens/HomeScreen"), {
  ssr: false,
});

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeScreen />
    </>
  );
};

export default Home;
